server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: jwt-spring-boot
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_USERNAME:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt: # openssl rand -base64 64
  signer-key: ${JWT_SIGNER_KEY:WL4EjoUlxLJDtuWBfz20NflAIgFjC6xNR6zmkrGh1HFy5rQNy9oIF/npA5nHyJLHp6Gc53srOY9F8FY0XGBGTg==}
  valid-duration: ${VALID_DURATION:0}
  refreshable-duration: ${REFRESHABLE_DURATION:0}
